### ISSUE TITLE
game freezing, issue with silence's turrets

### ISSUE THREAD

**Issue by Benjammin-n215** [Xylonity/Explosive-Enhancement-Reforged#4]
whenever a firework rocket shot by one of the turrets from the silence's turrets mod (i.e., the firework launcher), the game freezes for a moment and the console returns errors like that found below. seems to be related to an attempt to divide by zero?

mc version 1.20.1
forge version 47.3.12
silence's turrets version 2.6.7
occurs for all versions of explosive enhancement 1.20.1

[02/12/2024 23:55:44 PM] [Render thread/WARN] COM exception: Invalid Query: SELECT PERCENTUSAGE FROM Win32_PerfRawData_PerfOS_PagingFile
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_109752_(LevelRenderer.java:2492)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_109743_(LevelRenderer.java:2478)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientLevel.m_6493_(ClientLevel.java:594)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/explosiveenhancement@1.0.0/dev.xylonity.explosiveenhancement.ExplosiveHandler.spawnParticles(ExplosiveHandler.java:54)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/explosiveenhancement@1.0.0/dev.xylonity.explosiveenhancement.api.ExplosiveConfig.spawnParticles(ExplosiveConfig.java:39)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/explosiveenhancement@1.0.0/dev.xylonity.explosiveenhancement.api.ExplosiveConfig.spawnParticles(ExplosiveConfig.java:24)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Explosion.handler$dmb000$finalizeExplosion(Explosion.java:1542)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Explosion.m_46075_(Explosion.java:236)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientPacketListener.m_7345_(ClientPacketListener.java:1098)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundExplodePacket.m_5797_(ClientboundExplodePacket.java:91)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundExplodePacket.m_5797_(ClientboundExplodePacket.java:14)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
[02/12/2024 23:55:44 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02/12/2024 23:55:44 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[02/12/2024 23:55:44 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02/12/2024 23:55:44 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.12/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.12/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.12/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[02/12/2024 23:55:44 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[02/12/2024 23:55:44 PM] 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[02/12/2024 23:55:44 PM] Caused by: java.lang.ArithmeticException: / by zero
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.particle.ParticleEngine$MutableSpriteSet.m_5819_(ParticleEngine.java:553)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.particle.TextureSheetParticle.m_108339_(TextureSheetParticle.java:47)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/explosiveenhancement@1.0.0/dev.xylonity.explosiveenhancement.particle.custom.SmokeParticle.<init>(SmokeParticle.java:39)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/explosiveenhancement@1.0.0/dev.xylonity.explosiveenhancement.particle.custom.SmokeParticle$Provider.createParticle(SmokeParticle.java:85)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/explosiveenhancement@1.0.0/dev.xylonity.explosiveenhancement.particle.custom.SmokeParticle$Provider.m_6966_(SmokeParticle.java:74)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.particle.ParticleEngine.m_107395_(ParticleEngine.java:323)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.particle.ParticleEngine.m_107370_(ParticleEngine.java:311)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_109804_(LevelRenderer.java:2514)
[02/12/2024 23:55:44 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_109752_(LevelRenderer.java:2483)
[02/12/2024 23:55:44 PM] 	... 33 more
[02/12/2024 23:55:44 PM] [Render thread/FATAL] Error executing task on Client

**Comment by Xylonity** [comment]
Should be fixed in the latest version
